global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'demo-app'
    static_configs:
      - targets: ['app:8000']  # Metrics endpoint of the sample application

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # System metrics

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']  # Container metrics
